# Generated by Django 4.1.4 on 2022-12-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='epigrafe',
            field=models.TextField(default=None),
        ),
    ]
