# Generated by Django 4.1.4 on 2022-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contacto_redessociales_titulos_personal_news_mision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
